
version: '3.3'

services:
  cronjob:
    container_name: es-backup-cronjob
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backups:/backups
    env_file:
      - .env
  fileBrowser:
    container_name: es-backup-filebrowser
    image: filebrowser/filebrowser
    restart: always
    ports:
      - ${FILE_BROWSER_PORT}:80
    volumes:
        - backups:/srv

volumes:
  backups:
    driver: local
    driver_opts:
      type: none
      device: ${BACKUP_PATH}
      o: bind

